### ISSUE TITLE
addticket template - ideas

### ISSUE THREAD

**Issue by williamsmichael** [freehotsoup/freehotsoup#15]
**fields or models.py**
- Name * required
- Item * required
- ~~Quantity (initialized to 1)~~
- Delivery options or Pickup options
- Comments
- type - Donation or Request 

**other ideas**
- adjust HTML input type for address and time
- adjust dropdown values attributes to be the actual text value of the dropdown instead of an integer (e.g. value="needs delivered")
- 
-

**Comment by williamsmichael** [comment]
incorporated _pickup_address_ or _dropoff_address_ fields into the stages of the ticket. will that be okay or should it be a field for _addticket_? I can always demo at our next class

**Comment by 91ashika** [comment]
So at what stage do we provide address?

**Comment by williamsmichael** [comment]
it is currently after the **new** stage. it will be easy to add in if we keep it at the _addticket_. it does feel like if we leave it out of the _addticket_, we may need some more contact type of information (e.g. email, phone number, facebook username)?

what if we go back to your original idea to get some type of contact information but mask it?

**Comment by 91ashika** [comment]
I think it will be easy for the user to fill in everything on one go. So it would be better to keep address on addticket.html. I have only commented out the input fields for phone and email. So we could use it if required.

**Comment by williamsmichael** [comment]
issues #29 & #30 continue this issue
